TARGET_NAME = usart_demo
TARGET_TYPE = prj

# for project
PRJ_CSRC = main.c
PRJ_ASRC = 
PRJ_MODULES = avr/usart pdiusbd12
PRJ_DEFS = PDIUSBD12_DEBUG

export DEVICE = atmega16
export F_CPU = 8000000
export USART_BAUD = 115200
export USART_DATABIT = 8
export USART_STOPBIT = 1
export USART_PARITYBIT = NONE

include $(AVRLIB_INCLUDE_PATH)/Makefile_inc
